server:
  port: 7070
  address: 192.168.0.29
  context-path: /
  session:
    timeout: 20
      
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/oa
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

config:
  imageHost: http://192.168.0.29:7070/upload/